### ISSUE TITLE
Remeha Avanta Comfort?

### ISSUE THREAD

**Issue by baraka2** [rjblake/remeha#1]
Hi,
 first of all my english is bad but i hope you understand me :) 
 I have tried to kontact you here (https://www.domoticz.com/forum/viewtopic.php?f=34&t=14814&hilit=rjblake).
 I try to copy your awesome work with ESP8266 Connection to remeha here. The Adafruit HUZZAH ESP8266 is flashed but my remeha is not a calenta, it is a AvantaComfort. Recom Software shows "Avanta Comfort V1(P2)".
 my question: where do you find the hex codes transmit to remeha in remeha.ini under [Remeha Settings] ? is your script compatible with Remeha Avanta Comfort?

 thank you very much for your hard work!
 regards
 Adam

**Comment by rjblake** [comment]
Hi Adam,

Your English is great, so no problem (if Dutch, feel free to write in
Dutch; if Italian, French, Spanish or other... I'm afraid my understanding
is not good). There are a number of steps you need to go through to get the
scripts to work with other model boilers (e.g. AvantaComfort).

1. You need to connect a PC with some software (e.g. WireShark, Serial
Analyser, etc.) to trace the serial communications with the Remeha while
using the Remeha Recom software. This will allow you to reverse engineer
the codes Recom send to the boiler to get a response. I will check later
exactly which I used and perhaps try to make a video/instruction on how to
do.
2. Once you have this code, you need to edit the Remeha.INI file where it
shows the following:

[Remeha Settings]
remeha_sample =   "02FE010508020169AB03"; #Hex string to send to Calenta to
get it to respond with Sample Data

the string "02FE010508020169AB03" is the one that needs to be edited to
match your boiler (for the 'sample information only' - others are a little
more complex)).
3. You need to know what model the Recom software sees your boiler as (this
is shown in the bottom right or left of Recom window)
4. You then need to look at the related XML file from Recom to match to
codes and then edit the "remeha-samples.php" file to match these
5. Then repeat the same for the counters, identification, and parameters.
However, it depends on the information you want (samples and counters are
most likely enough)

I will try to write some more detailed instructions to help you; but it
will take me a week or two due to work at the moment

best regards
Richard

**Comment by rjblake** [comment]
No feedback received, so closing
